sudo: required
language: android
dist: trusty
env:
 global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=20
before_install:
 - chmod +x gradlew
before_script:
  # Create and start emulator.
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_EMULATOR_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_LEVEL
    #- sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
  licenses:
    - '.+'