sudo: required
language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
    - ANDROID_ABI=google_apis/arm64-v8a
    - ADB_INSTALL_TIMEOUT=20
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-29"
script:
    - ./gradlew assembleRelease
deploy:
  provider: releases
  on:
    branch: master
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT 
  api_key:
    secure: $GITHUB_API_KEY
  file: "app/build/outputs/apk/release/*"
  overwrite: true
  skip_cleanup: true
#after_deploy:
# - rm -rf app/build/outputs
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-29
    
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL   
    # Support library
    - extra-android-support
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-29

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-$ANDROID_EMULATOR_LEVEL
    #- sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_LEVEL
    #- sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
  licenses:
    - '.+'